vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerBridgeTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerRequestTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerTest.java
gRPC mandates to send a single response frame when an immediate occurs, the vertx server does not support it when a response trailer metadata is set, instead it will send a header frame and a trailer frame.
=> gRPC server will send header/trailer frames instead of a single frame when a trailers only case happens

vertx-grpc-client/src/main/java/io/vertx/grpc/client/GrpcClient.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/GrpcClientRequest.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientImpl.java, vertx-grpc-client/src/test/java/io/vertx/grpc/client/ClientRequestTest.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServerResponse.java
A simplified API to interact with a gRPC service:
```java
Future<T> fut = client.call(server, service, req -> req.send(item), resp -> resp.last());
```
```java
Future<List<T>> fut = client.call(server, service, req -> req.send(item), resp -> resp.collecting(Collectors.toList()));
```
=> GrpcClient API simplified call API to simplify interactions with a gRPC service 

vertx-grpc-client/src/main/java/io/vertx/grpc/client/GrpcClientResponse.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/VertxClientCall.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientRequestImpl.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientResponseImpl.java, vertx-grpc-client/src/test/java/io/vertx/grpc/client/ClientBridgeTest.java, vertx-grpc-client/src/test/java/io/vertx/grpc/client/ClientRequestTest.java, vertx-grpc-client/src/test/java/io/vertx/grpc/client/ClientTest.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/Utils.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServerResponse.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServiceBridgeImpl.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerBridgeTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerRequestTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerTest.java
- fixes https://github.com/eclipse-vertx/vertx-grpc/issues/54
- fixes https://github.com/eclipse-vertx/vertx-grpc/issues/51
=> Various fixes

pom.xml, vertx-grpc-common/src/main/asciidoc/index.adoc, vertx-grpc-it/pom.xml, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProtocPluginTest.java, vertx-grpc-protoc-plugin2/pom.xml, vertx-grpc-protoc-plugin2/src/main/asciidoc/plugin.adoc, vertx-grpc-protoc-plugin2/src/main/java/io/vertx/grpc/plugin/VertxGrpcGenerator.java, vertx-grpc-protoc-plugin2/src/main/resources/client.mustache, vertx-grpc-protoc-plugin2/src/main/resources/server.mustache
Create a protoc-plugin that uses the latest vertx-grpc-server and vertx-grpc-client library. This plugin enforces the use of RPCs that are only defined in the proto specification, ensuring greater consistency in communication between the server and client. Additionally, the generated code provides a clearer interface for the user and reduces boilerplate code
backport PR #48
=> Vertx grpc protoc plugin

vertx-grpc-server/src/main/asciidoc/server.adoc
=> GrpcServer can't be mounted in a Vert.x Web router

.github/workflows/ci-5.x.yml, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMediaType.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcMessageImpl.java, vertx-grpc-common/src/test/java/io/vertx/grpc/common/GrpcTestBase.java, vertx-grpc-server/pom.xml, vertx-grpc-server/src/main/asciidoc/server.adoc, vertx-grpc-server/src/main/generated/io/vertx/grpc/server/GrpcServerOptionsConverter.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServer.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServerOptions.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerRequestImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/BinaryServerTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/Interceptor.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/ServerTestBase.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/TestServiceImpl.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/TextServerTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/interop/Interceptor.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/interop/InteropITest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/interop/InteropServer.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/web/interop/TestServiceImpl.java, vertx-grpc-server/src/test/proto/empty.proto, vertx-grpc-server/src/test/proto/grpc-web-testing.proto, vertx-grpc-server/src/test/proto/messages.proto, vertx-grpc-server/src/test/proto/test.proto
Closes #55 
Each commit can be reviewed individually.
=> Implement gRPC-Web protocol

vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcReadStream.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcReadStreamBase.java
Deprecate `GrpcReadStream#collecting` in favour of `ReadStream#collect` that is the same method.
=> Deprecate GrpcReadStream#collecting in favour of ReadStream#collect

vertx-grpc-client/src/test/java/io/vertx/grpc/client/ClientMessageEncodingTest.java, vertx-grpc-context-storage/src/test/java/io/vertx/grpc/context/storage/ContextStorageTest.java
- retain the client as a field to avoid it being collected
- the context storage test closes the HTTP server and the vertx instance, since the vertx instance also closes the server, it seems that sometimes the explicit HTTP server close does not complete which indicates there might be a bug in vertx HTTP server close sequence which should be investigated
=> Improve tests failing in CI

vertx-grpc-client/src/main/java/io/vertx/grpc/client/GrpcClient.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientImpl.java, vertx-grpc-client/src/test/java/io/vertx/grpc/client/HttpClientWrappingTest.java
The gRPC client builds its own HTTP client. Since the HTTP client got new capabilities (service name resolution, unpooled connections), it makes sense to allow wrapping an existing HTTP client interface.
Modify the gRPC client to allow wrapping an existing HTTP client interface.
=> HTTP client updates

vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientImpl.java, vertx-grpc-client/src/main/java/io/vertx/grpcio/client/GrpcIoClient.java, vertx-grpc-client/src/main/java/io/vertx/grpcio/client/package-info.java, vertx-grpc-protoc-plugin2/src/main/resources/client.mustache, vertx-grpc-protoc-plugin2/src/main/resources/server.mustache, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServer.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpcio/server/GrpcIoServer.java, vertx-grpc-server/src/main/java/io/vertx/grpcio/server/package-info.java
Instead these methods are now available in GrpcIoClient/GrpcIoServer interfaces which extend GrpcClient/GrpcServer interfaces.
=> Deprecate GrpcClient/GrpcServer methods declaring a MethodDescriptor

vertx-grpc-docs/src/main/java/examples/VertxGreeterGrpcServer.java, vertx-grpc-docs/src/main/java/examples/VertxStreamingGrpcServer.java, vertx-grpc-protoc-plugin2/src/main/resources/server.mustache
Improve the server stub generator by decoupling the service method bind operations from the service method dispatch.
This allows to let the stub handle a request without requiring a bind.
=> Let the stub handle a request without requiring a server bind

vertx-grpc-client/src/main/java/io/vertx/grpc/client/GrpcClientOptions.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientImpl.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientRequestImpl.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientResponseImpl.java, vertx-grpc-client/src/test/java/io/vertx/tests/client/ClientRequestTest.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMessageDecoder.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcReadStream.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/InvalidMessageException.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/InvalidMessagePayloadException.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/MessageSizeOverflowException.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcReadStreamBase.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServerOptions.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerRequestImpl.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerRequestTest.java
Motivation:
The gRPC message decoder uses the default limit allowed by the gRPC HTTP/2 transport (2^32 bytes). The default maximum size should be smaller and configurable.
Changes:
Add options for configuring the maximum message size and use a lower default value (256KB) for both client and server. In addition an invalid message handler can be set on the GrpcReadStream to catch invalid message reports and let the application recover invalid messages. The invalid message handler can be triggered by a capacity overflow or a decoder exception.
Results:
gRPC server and client now uses a smaller default maximum message size which can be configured according to the application needs. Invalid message handler can also be set to catch invalid messages.
=> Set a configurable maximum payload size for the message decoder and add an invalid message handler to catch invalid messages

vertx-grpc-client/src/main/java/io/vertx/grpc/client/InvalidStatusException.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientResponseImpl.java, vertx-grpc-client/src/test/java/io/vertx/tests/client/ClientRequestTest.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProtocPluginTest.java
Motivation
The current handling of some futures of `GrpcClientResponse` will map the end future to a failure when the status is not `OK` with a mere message error.
We can instead more precisely handle it by providing a custom exception.
Changes
Introduce `InvalidStateException` and use an expectation to map an invalid status to such exception
=> Avoid masking invalid grpc status errors in GrpcClientResponse#last()

vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/Utils.java, vertx-grpcio-common/src/test/java/io/vertx/tests/common/UtilsTest.java
When using grpc web (with HTTP 1.1), the http headers are not lower cased when converting into grpc metadata. This means that they become inaccessible inside metadata since all the keys are converted to lower case on creation.
This erratic behaviour was observed in a couple of browsers that did not respect a lower case `authorization` header and transmitted upper case over the wire (confirmed on Wireshark).
This works fine for http2 since it's supposed to provide stronger case insensitive guarantees.
The test I added fails, if the `.toLowerCase()` is removed.
=> case insensitive grpc headers/metadata

vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMessage.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMessageDecoder.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMessageEncoder.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/ServiceMethod.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/ServiceName.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServer.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/TranscodingServiceMethod.java, vertx-grpcio-client/src/main/java/io/vertx/grpcio/client/GrpcIoClient.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/Utils.java
- `ServiceMethod`
- `TranscodingServiceMethod`
- `ServiceName`
- `GrpcMessage`
=> A couple of types are VertxGen annotated and could be instead data object or permitted

vertx-grpc-docs/src/main/java/examples/GreeterClient.java, vertx-grpc-docs/src/main/java/examples/GrpcClientExamples.java, vertx-grpc-docs/src/main/java/examples/StreamingClient.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProtocPluginTest.java, vertx-grpc-protoc-plugin2/src/main/resources/client.mustache
Motivation:
The generated streaming input client code generates a method consuming a handler of `GrpcReadStream` of messages.
This is not correct nor sufficient, error is not signaled and this is not Rx/Mutiny friendly.
Changes:
Change the handler of `GrpcReadStream` for a completable, so the error is properly signalled.
Add an alternative method that consumes directly a `ReadStream` of messages, so this will be clearly identified by Rx/Mutiny generators that will have the opportunity to use a Flowable/Multi instead.
=> Better streaming input client generation.

vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/BridgeMessageDecoder.java
Motivation:
The current implementation of the bridge uses a plain `ByteArrayInputStream` and then let protobuf parse the message. It turns out there is a `KnownLength` interface used by the parser to know the actual buffer size to be decoded and optimize the decoding process.
In addition we can use Netty `ByteBufInputStream` to avoid using `ByteArrayInputStream` and un-necessary copies.
Changes:
Swap usage of `ByteArrayInputStream` with a class that extends `ByteBufInputStream` and implement KnownLength.
=> Avoid un-necessary byte copies when decoding a Vert.x Buffer to a protobuf object and perform more optimal allocation

vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcReadStreamBase.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerTestBase.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/WorkerTest.java
Motivation:
`GrpcReadStream` has been using `InboundMessageChannel` as replacement of `InboundBuffer`. However it is incorrectly configured since as a server request handler it will consume events from the context event executor and not the event loop.
Changes:
Use the same event executor when building the `GrpcReadStream` inbound message channel.
=> Use the correct event executor for GrpcReadStream inbound message channel

vertx-grpc-docs/src/main/java/examples/GrpcServerExamples.java, vertx-grpc-docs/src/main/java/examples/grpc/Greeter.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterClient.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcClient.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcService.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterService.java, vertx-grpc-docs/src/main/java/examples/grpc/Streaming.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingClient.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcClient.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcService.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingService.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/DeadlineTest.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/JsonWireFormatTest.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProtocPluginTest.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProxyTest.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ReflectionTest.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/TranscodingTest.java, vertx-grpc-protoc-plugin2/src/main/java/io/vertx/grpc/plugin/VertxGrpcGeneratorImpl.java, vertx-grpc-protoc-plugin2/src/main/resources/base.mustache, vertx-grpc-protoc-plugin2/src/main/resources/client.mustache, vertx-grpc-protoc-plugin2/src/main/resources/server.mustache
This implies to modify the streaming pattern of the server to align with the client pattern which is to return a `Future<ReadStream<T>>`.
=> The generator should generate a common base interface for a service extended by the service and the client.

vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMessageDecoder.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMessageEncoder.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcWriteStreamBase.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/WriteStreamAdapter.java, vertx-grpc-common/src/test/java/io/vertx/tests/common/grpc/TestConstants.java, vertx-grpc-docs/src/main/java/examples/GrpcClientExamples.java, vertx-grpc-docs/src/main/java/examples/GrpcServerExamples.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcClient.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcService.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcClient.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcService.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/JsonWireFormatTest.java, vertx-grpc-protoc-plugin2/src/main/resources/grpc-client.mustache, vertx-grpc-protoc-plugin2/src/main/resources/grpc-service.mustache, vertx-grpc-reflection/src/main/java/io/vertx/grpc/reflection/GrpcServerReflectionV1Handler.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerRequestTest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerTest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/web/ServerTestBase.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/web/interop/InteropServer.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingGrpcServerRequest.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/BridgeMessageDecoder.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/BridgeMessageEncoder.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/Utils.java
Motivation:
The initial design of message codec assumed a single wire format that is protobuf.
We can reasonnably let codec supports multiple wireformats in order to simplify deployment of call handlers and the generated code.
Changes:
Message codec are now capable of handling the two wire formats.
Code generator and client/server changes have been implemented to support this.
=> Message codec should be capable to handle two wire formats.

.github/workflows/ci.yml
Motivation:
Added grpcurl installation for Linux runners and updated test execution to use a grpcurl-specific Maven profile on Linux. Non-Linux runners continue running standard Maven tests without changes.
=> Update CI workflow to install grpcurl and adjust test steps

vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientRequestImpl.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientResponseImpl.java, vertx-grpc-client/src/test/java/io/vertx/tests/client/ClientMessageEncodingTest.java, vertx-grpc-client/src/test/java/io/vertx/tests/client/ClientRequestTest.java, vertx-grpc-client/src/test/java/io/vertx/tests/client/ClientTest.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcHeaderNames.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerRequestImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/Http2GrpcServerRequest.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/Http2GrpcServerResponse.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/WebGrpcServerRequest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerMessageEncodingTest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerRequestTest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerTest.java, vertx-grpcio-client/src/test/java/io/vertx/tests/client/ClientBridgeTest.java
Motivation:
Introduced `GrpcHeaderNames` to standardize gRPC header names across the codebase, replacing strings.
Conformance:
=> Introduced `GrpcHeaderNames`

vertx-grpc-protoc-plugin2/src/main/resources/grpc-client.mustache
Motivation:
This pull request includes updates to the `vertx-grpc-protoc-plugin2` to improve the handling of asynchronous operations in gRPC client method templates. The changes primarily refactor the code to streamline the composition of futures for better error bubbling.
=> Fix grpc client error bubbling

vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcWriteStreamBase.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcService.java, vertx-grpc-protoc-plugin2/src/main/resources/grpc-service.mustache, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcHttpInvoker.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/MountPoint.java, vertx-grpc-server/src/main/java/module-info.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingGrpcServerResponse.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingInvoker.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingServiceMethodImpl.java, vertx-grpc-transcoding/src/main/java/module-info.java, vertx-grpc-transcoding/src/main/resources/META-INF/services/io.vertx.grpc.server.impl.GrpcHttpInvoker, vertx-grpc-transcoding/src/test/java/io/vertx/tests/transcoding/ServerTranscodingTest.java
Motivation:
Transcoding server requests are currently handled with a specific mount point acceptor for specific transcoding service methods.
We can make the mountpoint handle only the grpc server router mounting and leave the transcoding invocation in a separate SPI for creating transcoding invocation.
This will allow the transcoding invoker to handle transcoded requests without the need of specific metadata and simplify the deployment of transcoded handlers.
Changes:
The mount point now provides a list of paths to mount in the server internal router. When a transcoded request comes in, the invoker provides a transcoded using the service method metadata to handle the request/response messages.
Transcoded requests also now uses the new unified message encoder/decoder so they can decode …
=> Improve transcoding integration.

vertx-grpc-docs/src/main/asciidoc/server.adoc, vertx-grpc-docs/src/main/java/examples/GrpcServerExamples.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcClient.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcClient.java, vertx-grpc-server/src/main/generated/io/vertx/grpc/server/GrpcServerOptionsConverter.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServerOptions.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ProtocolSupportTest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/web/ServerTestBase.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/web/interop/InteropServer.java, vertx-grpc-transcoding/src/test/java/io/vertx/tests/transcoding/ServerTranscodingTest.java
Motivation:
The server has a flag configuring the support of gRPC-Web, it is also desirable to control other protocols as well.
Changes:
Replace the gRPC-Web boolean flag with a set of supported `GrpcProtocol`
=> Replace gRPC server options gRPC-Web flag with a generic set of supported protocols.

vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientRequestImpl.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientResponseImpl.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcMessageDeframer.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcReadStreamBase.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/Http2GrpcMessageDeframer.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerRequestImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/Http2GrpcServerRequest.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/WebGrpcServerRequest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/web/ServerTestBase.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/web/interop/InteropServer.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingGrpcServerRequest.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingMessageDeframer.java, vertx-grpc-transcoding/src/main/java/module-info.java, vertx-grpc-transcoding/src/test/java/io/vertx/tests/transcoding/ServerTranscodingTest.java
Motivation:
gRPC-Web-Text and application/json (transcoding) do not support message overflow check.
Changes:
Implement message overflow check in respective deframers.
=> Implement transcoding/text deframer message overflow check

vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcReadStreamBase.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcIo.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcService.java, vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcStub.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcIo.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcService.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcStub.java, vertx-grpc-docs/src/main/java/examples/grpc/VertxGreeterGrpc.java, vertx-grpc-docs/src/main/java/examples/grpc/VertxStreamingGrpc.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProtocPluginTestBase.java, vertx-grpc-protoc-plugin2/src/main/resources/grpc-io.mustache, vertx-grpc-protoc-plugin2/src/main/resources/grpc-service.mustache, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServerResponse.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/StatusException.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerRequestImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/main/java/module-info.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerRequestTest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerTest.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/stub/StreamObserverReadStream.java, vertx-grpcio-server/src/main/java/io/vertx/grpcio/server/impl/stub/ServerCalls.java, vertx-grpcio-server/src/test/java/io/vertx/tests/server/ServerBridgeTest.java
Motivation:
The current mapping of errors to status is currently not homogeneous (between vertx/io service generation) and lacks of a status exception allowing to set force a status to be set by the wrapper.
Changes:
Introduce `io.vertx.grpc.server.StatusException` that conveys the grpc status to be returned by the service when this exception is encountered.
=> Proper implementation of service error mapping to status mapping.

vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcMessageDecoder.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/WriteStreamAdapter.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/TranscodingTest.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingMessageDeframer.java, vertx-grpcio-client/src/main/java/io/vertx/grpcio/client/VertxClientCall.java, vertx-grpcio-client/src/main/java/io/vertx/grpcio/client/impl/GrpcIoClientImpl.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/BridgeMessageDecoder.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/BridgeMessageEncoder.java, vertx-grpcio-common/src/main/java/io/vertx/grpcio/common/impl/Utils.java, vertx-grpcio-server/src/main/java/io/vertx/grpcio/server/impl/GrpcIoServerImpl.java, vertx-grpcio-server/src/main/java/io/vertx/grpcio/server/impl/GrpcIoServiceBridgeImpl.java
Motivation:
The server grpc-io does not support properly transcoding requests due to lack of support for JSON in its decoders.
Changes:
Implement JSON support in grpc-io bridge message encoder/decoder. In addition reuse the bridge codec instead of using more or less the same code in the Utils class.
=> Decode/encode JSON wire format messages for grpc-io.

vertx-grpc-docs/src/main/java/examples/grpc/GreeterGrpcIo.java, vertx-grpc-docs/src/main/java/examples/grpc/StreamingGrpcIo.java, vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProtocPluginStubTest.java, vertx-grpc-protoc-plugin2/src/main/resources/grpc-io.mustache
Motivation:
When a grpc-io client stub builds a new context, it attempts to get the vertx context from the channel with a cast. This cast fails when the channel has been rewrapped by the abstract stub. Instead the context should simply be propagated by the current stub instance.
Changes:
Pass the current stub context when deriving a stub.
=> In a grpc-io client stub pass the vertx context when building a derived client

vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcMessageImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/GrpcServerResponse.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServiceBridgeImpl.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerBridgeTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerRequestTest.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerTest.java
Motivation:
Grpc allows to send separate HTTP headers, we should implement it.
Changes:
Add and implement `GrpcServerResponse#writeHead`
=> Add support for GrpcServerResponse headers writing.

vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/WebGrpcServerResponse.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/web/ServerTestBase.java
Motivation:
When a gRPC-Web response has no trailers set, the response fails with a `NullPointerException` since it assumes the `trailers` is not null.
=> Handle the gRPC-Web case of a response with no trailers set.

vertx-grpc-server/src/main/java/io/vertx/grpc/server/Service.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerImpl.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/LifecycleTest.java
Motivation:
Signal close lifecycle on a gRPC service which is useful for cleanup reasons when a service is unbound or a server closed.
=> Support close lifecycle for gRPC services.

vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientRequestImpl.java, vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientResponseImpl.java, vertx-grpc-client/src/test/java/io/vertx/tests/client/ClientRequestTest.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/GrpcWriteStream.java, vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcWriteStreamBase.java, vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServerResponseImpl.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerMessageEncodingTest.java, vertx-grpc-server/src/test/java/io/vertx/tests/server/ServerRequestTest.java, vertx-grpc-transcoding/src/main/java/io/vertx/grpc/transcoding/impl/TranscodingGrpcServerResponse.java
Motivation:
Server cancellation is using reset frames to signal stream cancellation, instead it should send a grpc status response whenever possible.
Changes:
Change server cancellation to send a grpc status response instead of sending a reset frame.
=> Server cancellation in the usual case should happen using the grpc status and not a reset.

vertx-grpc-server/src/main/java/io/vertx/grpc/server/impl/GrpcServiceBridgeImpl.java, vertx-grpc-server/src/test/java/io/vertx/grpc/server/ServerBridgeTest.java
Motivation:
The GrpcIo server bridge does not resume reading message when sending an error.
When an error happens in `StreamObserver.onNext`, the caller does not request a new message leading to stopping the consumption of messages.
Although the grpc response is properly sent to the client, this can lead to a dead-lock when the client sends many messages.
Changes:
When the GrpcIo server bridge sends a response, resume the stream adapter to release messages.
Avoid dispatching to `StreamObserver.onNext` when the stream is closed.
=> GrpcIo server bridge should resume reading message when sending an error

vertx-grpcio-context-storage/src/main/java/io/grpc/override/ContextStorageOverride.java, vertx-grpcio-context-storage/src/test/java/io/vertx/grpc/context/storage/ContextStorageTest.java, vertx-grpcio-context-storage/src/test/java/io/vertx/grpc/context/storage/CopiableObject.java, vertx-grpcio-context-storage/src/test/java/io/vertx/grpc/context/storage/MockContextStorage.java, vertx-grpcio-context-storage/src/test/resources/META-INF/services/io.vertx.core.spi.VertxServiceProvider
Motivation:
gRPC IO context storage requires to copy the vertx context, at the moment the copy is hand rolled and only affects the context local map.
Instead it should use the copying variant of duplicate.
Changes:
Replace the hand rolled duplication by the copying variant of `ContexInternal#duplicate`
=> Use the correct method in context storage context duplication.

vertx-grpc-docs/src/main/asciidoc/client.adoc, vertx-grpc-docs/src/main/asciidoc/ioclient.adoc, vertx-grpc-docs/src/main/asciidoc/ioserver.adoc, vertx-grpc-docs/src/main/asciidoc/iostorage.adoc, vertx-grpc-docs/src/main/asciidoc/server.adoc, vertx-grpc-docs/src/main/asciidoc/transcoding.adoc
Switch docs to use asciidoc tabs for dependency references
=> Switch docs to use asciidoc tabs for dependency references
